require('./src/ui-icon');
require('./src/ui-tooltip');
require('./src/ui-input');
require('./src/ui-checkbox');
require('./src/ui-actionbutton');
require('./src/ui-list');
require('./src/ui-popup');
require('./src/ui-dropdown');
require('./src/ui-search');
require('./src/ui-searchbox');
require('./src/ui-tooltip');
require('./src/ui-paginator');
require('./src/ui-minitags');
require('./src/ui-checklist');
require('./src/ui-arrow');
require('./src/ui-drawer');
require('./src/ui-form');
require('./src/date-picker/date-picker');
require('./src/date-picker/date-input');
require('./src/ui-radio');
require('./src/ui-radio-buttons');
// require('./src/date-picker/time-input');
// require('./src/date-picker/date-range-picker');
// require('./src/date-picker/date-range-input');
// require('./src/date-picker/date-range-inputs');
// require('./src/date-picker/date-time-input');

// window.paginate = require('./src/lib/paginate');
require('./src/lib/paginate');